name: linter Check

on:
  push:
    branches:
      - dev
      - production
  pull_request:
    branches:
      - dev
      - production

jobs:
  linter:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies & Run Linter
      run: |
        pip install poetry
        make install
        make lint